on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: codeberg-small

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup just
        uses: extractions/setup-just@v3

      - name: Install dependencies
        run: just install

      - name: Run Biome checks
        run: just check

      - name: Run tests
        run: just test

      - name: Build project
        run: just build
