on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: jaffa
    # container:
    #   image: ghcr.io/catthehacker/ubuntu:act-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Buildx builder
        run: |
          docker buildx create --name multi --use --driver docker-container || docker buildx use multi
          docker run --privileged --rm tonistiigi/binfmt --install arm64
          docker buildx inspect --bootstrap

      - name: Build image
        if: github.event_name == 'pull_request'
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t codeberg.org/studenterforpalestina/amro:latest \
            -t codeberg.org/studenterforpalestina/amro:${{ github.sha }} \
            --load .

      - name: Push image
        if: github.event_name == 'push'
        run: |
          docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_TOKEN }} codeberg.org

          docker buildx build \
            --platform linux/arm64 \
            -t codeberg.org/studenterforpalestina/amro:latest \
            -t codeberg.org/studenterforpalestina/amro:${{ github.sha }} \
            --push .
